---
sidebar: sidebar
permalink: aiqum-rest-api.html
keywords: active iq, unified manager, active iq unified manager
summary: Active IQ Unified Manager (formerly OnCommand Unified Manager) provides comprehensive management and monitoring for your ONTAP systems. It also includes a REST API to automate these tasks and enable third-party integration on supported systems.
---

= NetApp Active IQ Unified Manager REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Active IQ Unified Manager (formerly OnCommand Unified Manager) provides comprehensive management and monitoring for your ONTAP systems. It also includes a REST API to automate these tasks and enable third-party integration on supported systems.

// ONTAP®

== Benefits of the REST API

There are several benefits when using the REST API provided with Active IQ Unified Manager.

.Robust capabilities
By using the REST API, you can access the Active IQ Unified Manager capabilities to manage storage availability, capacity, security, protection, and performance risks.

.Automation consolidation
There is a single REST endpoint available to provision and manage your workloads. This provides a simple consolidated approach to implement service level objective policies, redirect events to third-party tools, and act as an API gateway to access the ONTAP REST API at an individual cluster level.

.Datacenter level automation of ONTAP management
You can automate the ONTAP provisioning and management workflows at a datacenter level. Monitoring and reporting can also be automated. This improves efficiency and provides a foundation for datacenter level aggregation.

== Get more information

There are several resources available to help you get started with the Active IQ Unified Manager REST API.

* https://docs.netapp.com/us-en/active-iq-unified-manager/api-automation/concept_get_started_with_um_apis.html[Getting started with Active IQ Unified Manager REST APIs^]

* https://library.netapp.com/ecmdocs/ECMLP2876865/html/index.html[Active IQ Unified Manager API documentation^]

* https://github.com/NetApp/Ansible-with-Active-IQ-Unified-Manager[NetApp modules for Ansible^]
