---
sidebar: sidebar
permalink: aiqum-rest-api.html
keywords: 
summary:
---

= NetApp Active IQ Unified Manager REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Active IQ Unified Manager (formerly OnCommand Unified Manager) provides comprehensive monitoring for your ONTAP systems. It can help to manage the storage availability, capacity, security, protection, and performance risks from a single interface. Active IQ Unified Manager includes a REST API to automate the management tasks and enable third-party integration on supported systems.

// ONTAP®

== Benefits of the REST API

There are several benefits to using the REST API provided with Active IQ Unified Manager.

.Automation consolidation
There is a single REST endpoint available to provision and manage your workloads. This provides a simple consolidated approach to implement service level objective policies, redirect events to third-party tools, and act as an API gateway to access the ONTAP REST API at an individual cluster level.

.Datacenter level automation
You can automate the ONTAP provisioning and management datacenter level workflows using AIQUM REST API. This also provides a foundation for datacenter level aggregation.

.Datacenter level monitoring and reporting
Automate ONTAP monitoring and reporting for your datacenter using AIQUM REST API.

== Get more information

There are several resources available to help you get started with the Active IQ Unified Manager REST API.

* https://docs.netapp.com/us-en/active-iq-unified-manager/api-automation/concept_get_started_with_um_apis.html[Getting started with Active IQ Unified Manager REST APIs^]

* https://library.netapp.com/ecmdocs/ECMLP2876865/html/index.html[Active IQ Unified Manager API documentation^]

* https://github.com/NetApp/Ansible-with-Active-IQ-Unified-Manager[NetApp modules for Ansible^]
