settings:
  name: NetApp Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false

sidebar:
  entries:
  - title: NetApp Automation docs
    url: /index.html
  - section: rn
  - section: solutions
  - title: Legal notices
    url: /legal-notices.html
