settings:
  name: NetApp Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false

sidebar:
  entries:
  - title: NetApp Automation docs
    url: /index.html
  - title: What's new
    url: /about/whats-new.html
  - section: solutions
  - title: Active IQ Unified Manager
    url: /aiqum-rest-api.html
  - section: api
  - section: support
  - title: Legal notices
    url: /legal-notices.html
