---
sidebar: sidebar
permalink: about/whats-new.html
keywords: whats new, enhancements, new features
summary: NetApp regularly updates the automation solutions, product REST APIs, and related software to bring you new features, enhancements, and bug fixes.
---

= What's new with NetApp Automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp regularly updates the automation solutions, product REST APIs, and related software to bring you new features, enhancements, and bug fixes.

== 26 July 2023

.Cloud Volumes ONTAP

Support for Cloud Volumes ONTAP is organized by the public cloud environment. A new solution is provided for the following cloud environment:

* link:../solutions/cvo-gcp-burst-to-cloud.html[Cloud Volumes ONTAP for Google Cloud - Burst to cloud]

== 04 June 2023

The NetApp https://console.bluexp.netapp.com/automationCatalog[BlueXP automation catalog^] is available through the BlueXP web user interface. The automation catalog provides access to solutions that can help you with the automated deployment and integration of NetApp products. The documentation for these solutions is organized in several different product or functional areas as described below.

.Amazon FSx for NetApp ONTAP

Two Amazon FSx for NetApp ONTAP solutions are provided as follows:

* link:../solutions/fsxn-burst-to-cloud.html[Amazon FSx for NetApp ONTAP - Burst to cloud]
* link:../solutions/fsxn-disaster-recovery.html[Amazon FSx for NetApp ONTAP - Disaster recovery]

.Azure NetApp Files

A solution is included to help you deploy Oracle with Azure NetApp Files:

* link:../solutions/anf-oracle.html[Oracle using Azure NetApp Files]

.Cloud Volumes ONTAP

Support for Cloud Volumes ONTAP is organized by the public cloud environment. Initial solutions are provided for two cloud environments as follows:

* link:../solutions/cvo-aws-burst-to-cloud.html[Cloud Volumes ONTAP AWS - Burst to cloud]
* link:../solutions/cvo-azure-burst-to-cloud.html[Cloud Volumes ONTAP Azure - Burst to cloud]
