---
sidebar: sidebar
permalink: about/whats-new.html
keywords: whats new, enhancements, new features
summary: NetApp regularly updates the Automation Catalog solutions and related software to bring you new features, enhancements, and bug fixes.
---

= What's new with NetApp Automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp regularly updates the Automation Catalog solutions and related software to bring you new features, enhancements, and bug fixes.

== 04 June 2023

The NetApp automation site provides a single location for documentation and other resources supporting the automation of the NetApp products and solutions. The initial launch of the site includes support for the new BlueXP automation catalog as well as links to various product REST APIs.

=== BlueXP automation catalog

The BlueXP automation catalog is now available from NetApp through the BlueXP web user interface. The automation catalog provides access to automation solutions that can help you with the automated deployment and integration of the NetApp products. The documentation for these solutions is provided at this site and organized in several product or functional areas as described below.

.Amazon FSx for NetApp

The documentation for two Amazon FSx for NetApp solutions is provided as follows:

* link:../solutions/fsxn-burst-to-cloud.html[FSxN - Burst to cloud]
* link:../solutions/fsxn-disaster-recovery.html[FSxN - Disaster recovery]

.Azure NetApp Files

xxx

.Cloud Volumes ONTAP for AWS

xxx

.Cloud Volumes ONTAP for Azure

xxx
