---
sidebar: sidebar
permalink: about/whats-new.html
keywords: whats new, enhancements, new features
summary: NetApp regularly updates the Automation Catalog solutions and related software to bring you new features, enhancements, and bug fixes.
---

= What's new with NetApp Automation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp regularly updates the automation solutions, product REST APIs, and related software to bring you new features, enhancements, and bug fixes.

== 04 June 2023

The NetApp automation site provides a single location for documentation and other resources supporting the automation of your NetApp products and cloud offerings. The initial launch of this site includes support for the new BlueXP automation catalog as well as various NetApp product REST APIs.

=== BlueXP automation catalog

The BlueXP automation catalog is available from NetApp through the BlueXP web user interface. The automation catalog provides access to solutions that can help you with the automated deployment and integration of the NetApp products. The documentation for these solutions is provided at this site and organized in several different product or functional areas as described below.

.Amazon FSx for NetApp

The documentation for two Amazon FSx for NetApp solutions is provided as follows:

* link:../solutions/fsxn-burst-to-cloud.html[FSxN - Burst to cloud]
* link:../solutions/fsxn-disaster-recovery.html[FSxN - Disaster recovery]

.Azure NetApp Files

xxx

.Cloud Volumes ONTAP

Support for Cloud Volumes ONTAP is provided and organized in two public cloud environments. The initial solutions include:

* link:../solutions/cvo-aws-burst-to-cloud.html[Cloud Volumes ONTAP for AWS deployment using Terraform]
