---
sidebar: sidebar
permalink: solutions/anf-oracle.html
keywords: bluexp automation catalog, netapp automation solutions, azure, azure netapp files, anf, oracle
summary: You can use this automation solution to provision Azure NetApp File (ANF) volumes and install Oracle on an available virtual machine. Oracle then uses the volumes for data storage.
---

= Install Oracle using Azure NetApp Files
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this automation solution to provision Azure NetApp File (ANF) volumes and install Oracle on an available virtual machine. Oracle then uses the volumes for data storage.

.About this solution

At a high level, the automation code provided with this solution performs the following actions:

* Set up a NetApp account on Azure
* Set up a storage capacity pool on Azure
* Provision the Azure NetApp Files volumes based on the definition
* Create the mount points
* Mount the Azure NetApp Files volumes to the mount points
* Install Oracle on the Linux server
* Create the listeners and database
* Create the Pluggable Databases (PDBs)
* Start the listener and Oracle instance
* Install and configure `azacsnap` to take a snapshot

.Before you begin

You must have the following to complete the installation:

* The automation solution packaged as file `Ora_ANF_Prov.zip`. You can download the file at the BlueXP web user interface.
* A Linux VM with the following characteristics:
** RHEL 8 (Standard_D8s_v3-RHEL-8)
** Deployed on the same Azure Virtual Network used for the Azure NetApp Files provisioning
* Azure account

The automation is based on Docker and Docker Compose. You need to install both of these on the Linux virtual machine as described below.

You should also register the VM with RedHat using the command `sudo subscription-manager register`. This will prompt you for your account credentials. If needed, you can create an account at /https://developers.redhat.com/.

== Step 1: Install and configure Docker

Install and configure Docker in a RHEL-8 Linux virtual machine.

.Steps

. Install the Docker software.
+
[source,cli]
dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
dnf install docker-ce --nobest -y

. Start Docker and display the version to verify the installation.
+
[source,cli]
systemctl start docker
systemctl enable docker
docker --version

. Add the required group and user.
+
Check if the group *docker* group exists in your Linux system. If it doesn't, create the group and user.
+
[source,cli]
sudo groupadd docker
sudo usermod -aG docker $USER

. Optionally activate your group and user definitions
+
If you created a new group and user, you need to activate the definitions. You can either logout and then back in, or execute the following command.
+
[source,cli]
newgrp docker

== Step 2: Install Docker Compose and the NFS utilities

Install and configure Docker Compose in the same RHEL-8 Linux virtual machine.

.Steps

. Install Docker Compose and display the version
+
[source,cli]
dnf install curl -y
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version

. Install the NFS utilities package.
+
[source,cli]
sudo yum install nfs-utils

== Step 3: Download the Oracle installer files

Download the required Oracle installation and patch files.

.Steps

. Sign in to your Oracle account as needed.

. Download the following files.
+
[cols="65,35"*,options="header"]
|===
|File
|Description
|LINUX.X64_193000_db_home.zip
|19.3 base installer
|p31281355_190000_Linux-x86-64.zip
|19.8 RU patch
|p6880880_190000_Linux-x86-64.zip
|opatch version 12.2.0.1.23
|azacsnap_installer_v5.0.run
|azacsnap installer
|===

. Place all the files in the directory `/tmp/archive` where they are needed for installation.

. Make sure all users on the database server have read, write, and execute access to the directory `/tmp/archive`.

== Step 4: Install the Oracle database using Docker

You can now install Oracle using the automation solution code.

.Steps

. Copy the solution file `Ora_ANF_Prov.zip` to the virtual machine where the automation code will be run.
+
[source,cli]
scp -i ~/<private-key.pem> -r Ora_ANF_Prov.zip user@<IP_ADDRESS_OF_VM>
+
Note the input parameter `private-key.pem` is your private key file used for Azure virtual machine authentication.

. Navigate to the correct directory and unzip the solution file.
+
[source,cli]
unzip Ora_ANF_Prov.zip

. Navigate to the directory `Ora_ANF_Prov` created with the unzip operation and list the files.
+
[source,cli]
ls -lt

== Step 5: Create an external volume

xxx

== Step 6: Validate the Oracle installation

You should confirm that the installation was successful.

.Steps

. Log in to Oracle server as `user` and display a list of the Oracle processes. This confirms the installation completed as expected and the Oracle database is running.
+
[source,cli]
ps -ef | grep ora

. Log in to the database to examine the database configuration settings and to confirm the PDBs were created properly.
+
[source,cli]
sqlplus / as sysdba
+
You should see output similar to the following:
+
----
SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle. All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0
----

. Execute a few simple SQL commands to confirm the database is available.
[source,sql]
select name, log_mode from v$database
show pdbs

== Step 7: Install azacsnap

xxx

== Step 8: Optionally migrate an on-premise PDB to the cloud 

xxx
