---
sidebar: sidebar
permalink: solutions/anf-oracle.html
keywords: bluexp automation catalog, netapp automation solutions, azure, azure netapp files, anf, oracle
summary: You can use this automation solution to provision Azure NetApp File (ANF) volumes and install Oracle on an available virtual machine. Oracle then uses the ANF volumes for data storage.
---

= Install Oracle with Azure NetApp Files
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this automation solution to provision Azure NetApp File (ANF) volumes and install Oracle on an available virtual machine. Oracle then uses the ANF volumes for data storage.

.About this solution

This solution consists of several major steps. The automation uses Terraform and Ansible, both of which must be installed on the Linux virtual machine as indicated below. All of the CLI command examples should be run on the Linux VM where Oracle is installed.

.Before you begin

You must have the following:

* The automation solution packaged as file `Ora_ANF_Prov.zip`. You can download the file at the BlueXP web user interface.
* A Linux VM with the following characteristics:
** RHEL 8 (Standard_D8s_v3)
** Public internet access
** Deployed on the same Azure Virtual Network that is used for the Azure NetApp Files provisioning
* Azure account

== Step 1: Install Terraform

Install Terraform which is needed to run the automation.

.Steps

. Using the Linux command line interface, navigate to an appropriate directory.

. Download the installation package.
+
[source,cli]
wget /https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip

. Extract the software.
+
[source,cli]
unzip terraform_1.4.2_linux_amd64.zip

. Remove the installer file.
+
[source,cli]
rm terraform_1.4.2_linux_amd64.zip

== Step 2: Install Ansible and the NFS utilities

Install Ansible and the NFS utilities package which are needed to run the automation.

.Steps

. Using the Linux command line interface, navigate to an appropriate directory.

. Install the Python package.
+
[source,cli]
sudo pip3 install ansible

. Install the NFS utilities.
+
[source,cli]
sudo yum install nfs-utils

== Step 3: Download the Oracle installer files

Download the required Oracle installation and patch files.

and place them in the /tmp/archive directory with read, write, and execute access for all users on DB server to be deployed. The automation tasks look for the named installation files in that directory for Oracle installation and configuration.


.Steps

. Sign in to your Oracle account as needed.

. Download the following files.
+
[cols="65,35"*,options="header"]
|===
|File
|Description
|LINUX.X64_193000_db_home.zip
|19.3 base installer
|p31281355_190000_Linux-x86-64.zip
|19.8 RU patch
|p6880880_190000_Linux-x86-64.zip
|opatch version 12.2.0.1.23
|===

. Place the files in the directory `/tmp/archive` where they are needed during installation.

. Make sure that all users on the database server to be deployed have read, write, and execute access to the directory `/tmp/archive`.

== Step 4: Install the Oracle database

You can now install Oracle using the automation solution.

.Steps

. Copy the solution file `Ora_ANF_Prov.zip` to the virtual machine where the automation will be run.
+
[source,cli]
scp -i ~/private-key.pem -r Ora_ANF_Prov.zip user@<IP_ADDRESS_OF_VM>

. Unzip the solution file.
+
[source,cli]
unzip Ora_ANF_Prov.zip

. List the files and confirm xxx

. Execute xxx

. Navigate to the directory xxx

. Source xxx

== Step 5: Validate the Oracle installation

You should confirm that the installation was successful.

.Steps

. Log in to Oracle server as oracle user and display a list the Oracle processes. This will indicate if installation completed as expected and the Oracle database is running.
+
`ps -ef | grep ora`

. Log in to the database to examine the database configuration settings and to confirm the PDBs were created properly.
+
`[oracle@localhost ~]$ sqlplus / as sysdba`
+
You should see output similar to the following:
+
----
SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle. All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0
----

. Execute a couple simple SQL commands to confirm the database is available.
[source,sql]
select name, log_mode from v$database
show pdbs
