---
sidebar: sidebar
permalink: solutions/anf-oracle.html
keywords: bluexp automation catalog, netapp automation solutions, azure, azure netapp files, anf, oracle
summary:
---

= Install Oracle with Azure NetApp FIles
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this automation solution to provision Azure NetApp File (ANF) volumes and install Oracle on a virtual machine. Oracle then uses the ANF volumes as data storage.

.About this solution

This solution consists of several major steps. The automation uses Terraform and Ansible, both of which must be installed on the Linux virtual machine as indicated below.

.Before you begin

You must have the following:

* A Linux VM with the following characteristics:
** RHEL 8 (Standard_D8s_v3)
** Public internet access
** Deployed on the same Azure Virtual Network that is used for the Azure NetApp Files provisioning
* Azure account

== Step 1: Install Terraform

Install Terraform which is needed to run the automation.

.Steps

. Using the Linux command line interface, navigate to an appropriate directory.

. Download the installation package.
+
[source,cli]
wget /https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip

. Extract the software.
+
`unzip terraform_1.4.2_linux_amd64.zip`

. Remove the installer file.
+
`rm terraform_1.4.2_linux_amd64.zip`

== Step 2: Install Ansible and NFS utilities

Install Ansible and the NFS utilities package which are needed to run the automation.

.Steps

. Using the Linux command line interface, navigate to an appropriate directory.

. Install the Python package.
+
`sudo pip3 install ansible`

. Install the NFS utilities.
+
`sudo yum install nfs-utils`

== Step 3: Download the Oracle installer files

xxx

== Step 4: Install the Oracle database

xxx

== Step 5: Validate the Oracle installation

You should confirm that the installation was successful.

.Steps

. Log in to Oracle server as oracle user and display a list the Oracle processes. This will indicate if installation completed as expected and the Oracle database is running.
+
`ps -ef | grep ora`

. Log in to the database to examine the database configuration settings and to confirm the PDBs were created properly.
+
`[oracle@localhost ~]$ sqlplus / as sysdba`
+
You should see output similar to the following:
----
SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle. All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0
----

. Execute a simple xxx
