---
sidebar: sidebar
permalink: solutions/bac-overview.html
keywords: bluexp automation catalog, automation catalog, overview, introduction
summary:
---

= Overview of the BlueXP automation catalog
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The BlueXP automation catalog is a collection of automation solutions available to NetApp customers, partners, and employees. Some of the features and benefits of the catalog are described below.

Single location for your automation needs::

You can access the https://console.bluexp.netapp.com/automationCatalog[BlueXP automation catalog^] through the BlueXP web user interface. This provides a single location for the scripts, playbooks, and modules needed to enhance the automation and operation of your NetApp products and services.

Solutions are created and tested by NetApp::

All the automation solutions and scripts have been created and tested by NetApp. Each solution targets a specific customer use case or request. Most focus on integration with the NetApp file and data services.

Documentation::

Each of the automation solutions includes associated documentation to help you get started. While the solutions are accessed through the BlueXP web interface, all the documentation is available at this site. The documentation is organized based on the NetApp products and cloud services.

Solid foundation for the future::

NetApp is committed to helping our customers improve and streamline the automation of their data centers and cloud environments. We expect to continue enhancing the BlueXP automation catalog to address customer requirements, technology changes, and continued product integration.

We want to hear from you::

The NetApp Customer Experience Office (CXO) automation team would like to hear from you. If you have any feedback, issues, or feature requests, please send an email to mailto:ng-cxo-automation-admins@netapp.com[CXO automation team].
