---
sidebar: sidebar
permalink: solutions/fsxn-burst-to-cloud.html
keywords: bluexp automation catalog, netapp automation solutions, fsxn, burst to cloud
summary: You can use this automation solution to provision Amazon File Services for NetApp with volumes and an associated FlexCache.
---

= Amazon FSx for NetApp - Burst to cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use this automation solution to provision Amazon File Services for NetApp with volumes and an associated FlexCache.

[NOTE]
For convenience and brevity, Amazon File Services for NetApp will be referred to as *FSxN*.

.About this solution

At a high level, the automation code provided with this solution performs the following actions:

* Provision a destination FSxN file system
* Provision Storage Virtual Machines (SVMs) for the file system
* Create a cluster peering relationship between the source and destination systems
* Create an SVM peering between the source system and destination system for FlexCache
* Optionally create FlexVol volumes in FSxN (optional)
* Create a FlexCache volume in FSxN with the source pointing to the on-prem storage

The automation is based on Docker and Docker Compose which must be installed on the Linux virtual machine as described below.

.Before you begin

You must have the following to complete the FSxN and FlexCache provisioning and configuration:

* The automation solution packaged as file `AWS_FSxN_BTC.zip`. You can download the file at the BlueXP web user interface.
* Network connectivity between the source and destination systems.
* A Debian-based Linux VM deployed on the same VPC subsets used for the FSxN provisioning.
* An AWS account.

== Step 1: Install the Docker and Docker Compose software

Install Docker and Docker Compose on the Debian Linux distribution VM.

.Steps

. Prepare to install Docker.
+
[source,cli]
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent softwareproperties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64]
https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update

. Install and verify Docker by checking the version.
+
[source,cli]
sudo apt-get install docker-ce docker-ce-cli containerd.io
docker --version

. If the Linux group `docker` does not already exist, you need to add the group and associated user.
[source,cli]
sudo groupadd docker

. Install Docker-Compose.
[source,cli]

== Step 2: Extract and prepare the Docker files

. Copy the solution file `AWS_FSxN_BTC.zip` to the virtual machine where the automation code will be run.
+
[source,cli]

. Unzip the solution file.
+
[source,cli]
unzip AWS_FSxN_BTC.zip

== Step 3: Create an external volume

External Volume to keep the Terraform state files and other important files persistent. Make sures that the files are avaiable for Terraform to run the workflow and deployments.

. 

== Step 4: Provision FSxN and FlexCache

XXX

== Step 5: Destroy FSxN and FlexCache

XXX
