---
sidebar: sidebar
permalink: solutions/ontap-day01-prepare.html
keywords: bluexp automation catalog, netapp automation solutions, ontap day 0/1, prepare
summary:
---

= Prepare to use the ONTAP day 0/1 solution
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Before you deploy the automation solution you must prepare the ONTAP environment and install and configure Ansible.

== Initial planning considerations

.Requirements and skills
 
* You must be competent in using Ansible automation software.
* You must have access to ONTAP software either on-premises or through an ONTAP simulator.

.Planning considerations

Before you deploy the solution, you must decide:

* The location where you are going to run the Ansible control node.
* The ONTAP system, either on-premises hardware or an ONTAP simulator. 
* Whether or not you will require customization. 


== Prepare the ONTAP system

Whether you are using an on-premises ONTAP system or Simulate ONTAP, you must prepare the environment before you can deploy the automation solution. 

=== Optionally install and configure Simulate ONTAP

If you want to deploy this solution through an ONTAP simulator, you must download and run Simulate ONTAP. 

.Before you begin

* You must download and install the VMWare hypervisor that you are going to use to run Simulate ONTAP. 
+
** If you have a Windows or Linux OS, use VMWare Workstation.
** If you have a Mac OS, use VMWare Fusion.
+
NOTE: If you are using a Mac OS, you must have an Intel processor. 

.Steps

Use the following steps to install two ONTAP simulators in your local environment:

. Download Simulate ONTAP from the link:https://mysupport.netapp.com/site/tools/tool-eula/simulate-ontap[NetApp support site^]
+
NOTE: Although you will install two simulators, you only need to download one copy of the software.

. If it is not already running, start up your VMWare application.
. Locate the simulator file that was downloaded and right click to open it with
the VMWare application.
. Set the name of the first ONTAP instance 
. Wait for the simulator boot up and follow the directions to create a single
node cluster.
. Repeat steps 2 through 6 for the second ONTAP instance.

. Configure each instance for use.
+
From each cluster, run the following commands: 
[source,cli]
::> security unlock -username <user_01>
::> security login password -username <user_01>
::> set -priv advanced
::> systemshell local
::> <Cluster-01>::> disk assign -all -node <Cluster-01>-01

=== State of the ONTAP system

You must verify the initial state of the ONTAP system, whether it is on-premises or running through an ONTAP simulator. 

Verify that the following ONTAP system requirements are met: 

* ONTAP is installed and running but no cluster is defined yet
* The network reachable
* You must have admin credentials
* The MOD banner is displayed with the management address

== Install the required automation software

This section provides information on how to install Ansible and prepare the automation solution for deployment. 

=== Install Ansible

Refer to link:https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible/[Getting Started with NetApp and Ansible: Install Ansible^] for the steps to install Ansible.

NOTE: Ansible must be installed on the control node of the system. 

=== Download and prepare the automation solution

You can use the following steps to download and prepare the automation solution for deployment.

. Download the link:https://console.bluexp.netapp.com/automationCatalog[ONTAP day 0/day1^] automation solution through the BlueXP web UI. The solution is packaged as `ONTAP_DAY0_DAY1.zip`.
+
. Extract the zip folder and copy the files to the desired location on the control node within your Ansible environment.

== Initial Ansible framework configuration

Perform some initial configuration of the Ansible framework:

. Navigate to `playbooks/inventory/group_vars/all`
. Modify the following Ansible files: 
* clusters.yml 
* vault.yml 
* cfg.yml - Set the file path for `log2file` and set `show_request`
under `cfg` to `True` to display the `raw_service_request`.
. Navigate to `playbooks/inventory/hosts` and set a valid Python interpreter.
+
NOTE: Each file listed contains comments with instructions on how to modify them according to your requirements. 

. Deploy the `framework_test` service:
+
The following command runs the `na_ontap_info` module with a gather subset value of
`cluster_identity_info`. This validates that the basic configuration is correct and verifies that you can communicate with the cluster. 
+
[source,cli]
ansible-playbook -i inventory/hosts site.yml -e cluster_name=<CLUSTER_NAME>
-e logic_operation=framework-test
+
Run the command for each cluster that you need. 
+
If successful, you should see output similar to the following example:
+
----
PLAY RECAP *********************************************************************************
localhost : ok=12 changed=1 unreachable=0 failed=0 skipped=6
The key is ‘rescued=0’ and ‘failed=0’..
----

