---
sidebar: sidebar
permalink: solutions/ontap-day01-overview.html
keywords: bluexp automation catalog, netapp automation solutions, ontap day 0/1, overview, introduction
summary:
---

= Overview of the ONTAP day 0/1 solution
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP day 0/1 automation solution to deploy and configure an ONTAP cluster using Ansible. The solution is available at the BlueXP automation catalog site.

== Flexible ONTAP deployment options

xxx
>> Two options

.Local ONTAP simulator

xxx
>> ONTAP simulator you can download from NetApp
>> Run on a local VMware hypervisor (either VMware Workstation or Fusion)

.On-premises hardware

>> Real ONTAP FAS/AFF
>> On-premises

== Layered design

>> Layered structure
>> Benefit of knowing, then able to custoize
>> See README.pdf for content in two sections below
>> Must rewrite and simplify the top paragraph and remove "ARC"
>> Remove the last section "Configuration" and move to bottom of the the "Deploy" topic

.Logic layer

xxx

.Execution layer

xxx

== Support for customization

xxx
>> Can customize the solution in various ways
>> Modify the playbooks and other Ansible-related files
>> Add roles
>> Link to the customization topic
>> See latest email with list of files
